AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EndpointName:
    Type: String
    Default: sms-spam-classifier-mxnet-2022-04-19-13-44-09-942
    Description: Endpoint name for ML model
Metadata:
  'AWS::CloudFormation::Designer':
    6e75bd59-bc85-4cab-94b4-a661f0bcf6e9:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
    496872d8-8443-4935-86d7-5033b5b839c3:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 60
      z: 1
      embeds: []
    0bf06b4a-f927-4c3e-9a08-8013090ce084:
      size:
        width: 60
        height: 60
      position:
        x: 420
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - 496872d8-8443-4935-86d7-5033b5b839c3
    9ebd078e-88e6-4715-a3fd-94fd9330f60e:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - 496872d8-8443-4935-86d7-5033b5b839c3
    2616917c-3b0b-4244-8759-22854ba585aa:
      size:
        width: 60
        height: 60
      position:
        x: 510
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - 496872d8-8443-4935-86d7-5033b5b839c3
    06baf641-ce16-4144-8431-915487c8b8fd:
      size:
        width: 60
        height: 60
      position:
        x: 666.2566411822835
        'y': 160.11427481492586
      z: 0
      embeds: []
    72aa6a64-6634-4e92-8711-fb52b0db1cdf:
      size:
        width: 60
        height: 60
      position:
        x: 650.3392657639621
        'y': 33.04718120077146
      z: 0
      embeds: []
      isassociatedwith:
        - 06baf641-ce16-4144-8431-915487c8b8fd
    a02599ef-5f1e-46ac-aa33-e5f6393d0581:
      size:
        width: 60
        height: 60
      position:
        x: 228.9308787410861
        'y': 182.40199429022948
      z: 0
Resources:
  ProcessEmailLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: lambdascc
        S3Key: L1-a97f0e83-4065-4f65-b4cd-6171df808487.zip
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.9
      Environment:
        Variables:
          ENDPOINT_NAME: !Ref EndpointName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6e75bd59-bc85-4cab-94b4-a661f0bcf6e9
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "lambda.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
            }
        ]
    }
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 496872d8-8443-4935-86d7-5033b5b839c3
  SagemakerPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: SagemakerPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action: 'sagemaker:InvokeEndpoint'
            Resource: 'arn:aws:sagemaker:*:197953848710:endpoint/*'
      Roles:
        - Ref: LambdaRole
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0bf06b4a-f927-4c3e-9a08-8013090ce084
  EmailReadPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: EmailReadPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action: 's3:GetObject'
            Resource: '*'
      Roles:
        - Ref: LambdaRole
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2616917c-3b0b-4244-8759-22854ba585aa
  SendEmailPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: SendEmailPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action: 'ses:SendEmail'
            Resource: '*'
      Roles:
        - Ref: LambdaRole
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9ebd078e-88e6-4715-a3fd-94fd9330f60e
  S3EmailBucket:
    Type: 'AWS::S3::Bucket'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 06baf641-ce16-4144-8431-915487c8b8fd
  S3EmailBucketPutPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3EmailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSESPuts
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3EmailBucket
                - /*
            Condition:
              StringEquals:
                'AWS:SourceArn': >-
                  arn:aws:ses:us-east-1:197953848710:receipt-rule-set/ccbdreceivemail:receipt-rule/saves3
                'AWS:SourceAccount': '197953848710'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 72aa6a64-6634-4e92-8711-fb52b0db1cdf
  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt ProcessEmailLambda.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a02599ef-5f1e-46ac-aa33-e5f6393d0581
